const embeddedArchive = process.env.ARTICLE_ARCHIVE_EMBED === '1';

module.exports = embeddedArchive ? {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
} : {
  docsSidebar: [
    'analysis',
    'reading-paths',
    {
      type: 'doc',
      id: 'articles/index',
      label: 'All Articles',
      className: 'sidebar-all-articles-button',
    },
    {
      type: 'category',
      label: 'Articles',
      collapsed: true,
      link: {type: 'doc', id: 'articles/index'},
      items: [{type: 'autogenerated', dirName: 'articles'}],
    },
    {
      type: 'category',
      label: 'Labs',
      collapsed: false,
      items: [
        'labs/index',
        {
          type: 'category',
          label: 'AI Security',
          collapsed: true,
          items: [
            'labs/llm-agent-attack-lab',
            'labs/vulnerable-ai-lab',
          ],
        },
        {
          type: 'category',
          label: 'AI-Assisted Pentest',
          collapsed: true,
          items: [
            'labs/hackerai-metasploitable-lab',
            'labs/hexstrike-home-network-lab',
            'labs/hexstrike-metasploitable-lab',
            'labs/hexstrike-subnet-compromise-lab',
            'labs/hexstrike-webapp-pentest-lab',
            'labs/hexstrike-wireless-pentest-lab',
          ],
        },
        {
          type: 'category',
          label: 'Active Directory',
          collapsed: true,
          items: [
            'labs/active-directory-manual-lab',
            'labs/active-directory-one-prompt-lab',
            'labs/active-directory-pentest-lab',
            'labs/adcs-esc8-lab',
            'labs/ai-black-box-active-directory-lab',
          ],
        },
        {
          type: 'category',
          label: 'CTI Emulation',
          collapsed: true,
          items: [
            'labs/operation-dragonrx-attack-playbook',
            'labs/operation-dragonrx-lab-architecture',
          ],
        },
        {
          type: 'category',
          label: 'Cloud',
          collapsed: true,
          items: [
            'labs/ai-web-cloud-pentest-lab',
            'labs/cloud-pentest-walkthrough',
            'labs/gcp-penetration-testing-attack-guide',
            'labs/vulnerable-cloud-pentest-lab-terraform',
            'labs/vulnerable-gcp-pentest-lab',
          ],
        },
        {
          type: 'category',
          label: 'Kubernetes',
          collapsed: true,
          items: [
            'labs/black-box-kubernetes-pentest-playbook',
            'labs/one-prompt-kubernetes-pentest',
            'labs/vulnerable-kubernetes-lab',
          ],
        },
        {
          type: 'category',
          label: 'Mobile Security',
          collapsed: true,
          items: [
            'labs/android-app-analysis-lab',
            'labs/one-prompt-android-pt-lab',
            'labs/vulnerable-android-app-owasp-mstg',
          ],
        },
        {
          type: 'category',
          label: 'Tooling',
          collapsed: true,
          items: [
            'labs/dockerized-ai-host-vulnerability-assessment',
          ],
        },
        {
          type: 'category',
          label: 'Vulnerable Infrastructure',
          collapsed: true,
          items: [
            'labs/vulnerable-iis-sharepoint-fluent-bit-lab',
            'labs/vulnerable-ubuntu-server-lab',
            'labs/vulnerable-windows-10-lab',
            'labs/vulnerable-windows-vm',
          ],
        },
        {
          type: 'category',
          label: 'Vulnerable Web',
          collapsed: true,
          items: [
            'labs/safe-dvwa-ansible-lab',
          ],
        },
      ],
    },
  ],
};
