#!/usr/bin/env node
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const read=p=>readFileSync(resolve(root,p),'utf8');
const ledger=JSON.parse(read('research/anomaly-revision/issues.json'));
const functional=JSON.parse(read('research/anomaly-validation/results/functional-results.json'));
const count=Object.fromEntries([...new Set(ledger.issues.map(i=>i.status))].map(s=>[s,ledger.issues.filter(i=>i.status===s).length]));
let text=`# Anomaly research: reconciled factual and implementation audit\n\nRevision date: ${ledger.reviewed_at}. Author: Andrey Pautov. Baseline: \`${ledger.baseline_commit}\`.\n\n## Evidence boundary\n\nThis replaces the earlier blanket-open audit with finding-level dispositions. ${ledger.scope} Additional findings and external dependencies are recorded separately. A textual correction is not a production validation result. This is an author/assistant revision, not independent peer-review certification.\n\nThe article now distinguishes source-reported incidents, inferred detectors, synthetic functional fixtures, public lab-recording replay and a synthetic statistical experiment. No production accuracy percentage is assigned. The Medium edition has not been modified by this revision.\n\n## Current validation\n\n- Canonical KQL files: 8, using explicit normalized schemas rather than unspecified native connector tables.\n- Real Kusto functional execution: ${functional.functional_passed?'passed':'not passed'}; ${functional.synthetic_tests.filter(x=>x.passed).length}/${functional.synthetic_tests.length} synthetic regression cases.\n- Offline counterexamples: ${functional.offline_checks.filter(x=>x.passed).length}/${functional.offline_checks.length}.\n- Public recordings: ${functional.public_recordings.length}, pinned to a repository commit and verified SHA-256 digests. These do not provide a representative negative corpus or per-event malicious labels.\n- Native Sentinel ingestion, Splunk execution, production precision/recall and automated containment safety: not established.\n\nThe single-ticket Kerberoasting recording produces no breadth-rule match. DCSync records without suitable logons retain unresolved source IPs. Neither limitation is repaired by fabricating events or enrichment.\n\n## Dispositions\n\n`;
for(const [status,n] of Object.entries(count))text+=`- ${status}: ${n}\n`;
text+='\nThese counts are ledger entries, not unique defects, detection accuracy, or a percentage of research correctness.\n\n| ID | Priority | Finding | Resolution and evidence location | Status |\n|---|---|---|---|---|\n';
const cell=x=>String(x).replaceAll('|','\\|').replaceAll('\n',' ');
for(const i of ledger.issues)text+=`| ${i.id}${i.overlaps?' (overlaps '+i.overlaps.join(', ')+')':''} | ${i.priority} | ${cell(i.original_finding)} | ${cell(i.resolution)} **${cell(i.location)}** | ${i.status} |\n`;
text+='\n## Reproduction and supporting artifacts\n\nSee `research/anomaly-validation/README.md` in the source repository, the downloadable `anomaly-validation/bundle.json`, canonical query files, functional outputs, dataset manifest and synthetic-study inputs/results. Query hashes bind the reported engine run to the published snippets. Historical query exports are explicitly superseded in `anomaly-historical-code.md`.\n\n## Publication boundary\n\nThe original article URL, existing article routes/canonicals, all prior heading anchors, 15 anomaly tags and 30 incident mappings are preserved. All 44 original images, including the old cover, remain in a clearly superseded historical appendix. They have not received a new visual fact audit and are not current implementation guidance. A separate set of 43 author-reviewed, source-linked diagrams is now placed inline; its desktop/mobile SVGs and numerical inputs are bound by the `anomaly-visuals/manifest.json` evidence manifest. This replacement does not certify the historical images or establish production accuracy.\n\nBuild checks and local browser verification are reported separately from query execution. A repository revision is not evidence of deployment or of a synchronized Medium edition.\n';
const files=[['static/research/anomaly-fact-audit.md',text],['static/research/anomaly-validation/issues.json',JSON.stringify(ledger,null,2)+'\n']];
for(const [p,value] of files){if(process.argv.includes('--check')){if(read(p)!==value)throw Error('Stale audit '+p);}else writeFileSync(resolve(root,p),value);}
console.log(`Reconciled audit: ${ledger.issues.length} entries; ${JSON.stringify(count)}`);
