#!/usr/bin/env node
// Historical first-edition report. For uploaded replacements use report_anomaly_uploads.mjs.
import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
const root=resolve(fileURLToPath(new URL('..',import.meta.url)));
const read=p=>readFileSync(resolve(root,p),'utf8'),json=p=>JSON.parse(read(p));
const dir='reports/anomaly-visuals-20260921';
const manifest=json('static/research/anomaly-visuals/manifest.json'),checks=json(dir+'/verification.json');
if(manifest.figures.length!==43||manifest.figures.some(f=>f.upload))throw Error('This report is a historical 43-SVG-figure snapshot. Use report_anomaly_uploads.mjs for the current edition.');
const browser=json(dir+'/browser-validation.json');
const safe=s=>s.replaceAll('|','\\|');
let text=`# Anomaly research: inline infographic replacement\n\nLocal implementation and verification report. **Not committed, pushed or deployed by this task.** The already published edition remains unchanged until a separate release.\n\n## Delivered\n\n- ${manifest.figures.length} new source-linked figures, placed inline in reading order: concepts and base rates, 14 operational families plus multi-event correlation, ATT&CK mapping, 12 campaign summaries, telemetry, DNS entropy, four credential techniques, observability, analytic validation and statistical results.\n- 86 self-contained SVGs: an 800-pixel desktop layout and a separately reflowed 400-pixel narrow layout for every figure.\n- One local PNG cover, bound to its source SVG by SHA-256; no raster-image generation model was used.\n- Every figure has an evidence label, caption, source links, accessible text equivalent and full-size link. Current figures are not hidden in accordions.\n- All 44 original images, including the old cover, remain in the historical appendix. The catalog correctly counts 87 image instances: 43 current + 44 historical. Existing URLs, anchors, topic tags, incident cards and maintained query files are preserved.\n\nThe writer skill informed the distinction between source-reported incidents, author-proposed detection interpretations, exact explanatory arithmetic, recorded execution results and synthetic statistics. The graphics do not upgrade the evidence status of their inputs.\n\n## Validation\n\nOverall local gate: **${checks.passed&&browser.passed?'PASS':'FAIL / INCOMPLETE'}**.\n\n| Check | Result | Evidence |\n|---|---|---|\n`;
for(const c of checks.steps)text+=`| ${c.id} | ${c.exit_code===0?'PASS':'FAIL'} (${c.seconds}s)${c.identical_visual_assets?`; ${c.identical_visual_assets} identical build assets`:''} | [${c.log}](${c.log}) |\n`;
text+=`\nBrowser asset checks: ${browser.assets.length} SVG variants; ${browser.failures.length} clipping/overlap failures. Article configurations: ${browser.article.filter(x=>x.width).length}, covering 390, 768 and 1440 pixels in light/dark themes. The checker verifies image loading, responsive variants, aspect ratios, page overflow, 43 inline figures, all 44 preserved historical images and JavaScript errors. See [machine-readable gate](verification.json), [browser report](browser-validation.json), and contact sheets [1](contact-sheet-1.png), [2](contact-sheet-2.png), [3](contact-sheet-3.png), [4](contact-sheet-4.png), [5](contact-sheet-5.png), [6](contact-sheet-6.png).\n\n## Factual and numerical review\n\n- Incident figures mirror the revised manuscript, with separate source-reported and inferred panels. They do not invent a victim timeline or claim a proposed rule detected an incident.\n- The source review rechecked MITRE's v19/v19.2 release notes, Microsoft event/Sysmon references, Midnight Blizzard and Volt Typhoon reporting, Mandiant MOVEit/SUNBURST/UNC3944/APT41 reports, Unit 42 RDAT, the DFIR Report Conti case and SentinelOne 3CX reporting.\n- CISA's direct PDF/advisory fetches returned access errors in this run. Indexed content from the same official CSRB PDF supports the Big Yellow Taxi/MailItemsAccessed account; CISA's indexed AA22-277A PDF supports the unnamed-actor Impacket case. This is not reported as a successful new full-document download. Original primary links are retained.\n- Base-rate example: 90 / (90 + 10,000) = 0.89% precision. These are assumed explanatory inputs.\n- DNS examples are computed from their displayed labels: aaaa = 0, abab = 1, abcd = 2 bits/character. High character entropy is not a maliciousness verdict.\n- Functional/replay figures read the existing report: 34/34 KQL cases, 8/8 offline checks; replay outputs 4/11 DCSync, 24/32 LSASS and 0/1 Kerberoasting input records. Output rows are not true-positive counts. No new KQL run is claimed.\n- Statistical charts read the committed generated dataset's results. The gate removes 77 false alerts and seven true alerts relative to ungated entity-MAD. Both precision and recall, plus TP/FP/FN/TN, remain visible. No production performance is claimed.\n\n## Improvements made during verification\n\nActual browser geometry caught two wrapping problems; both were corrected. Four-step flows were widened into a two-row desktop layout for readable labels. The embedded archive gate caught new-tab behavior on internal SVG links; the component now follows same-origin navigation policy. Neither a compiler success nor a green source test was treated as a substitute for browser checks.\n\n## Placement inventory\n\n| Figure | Graphic | Article location | Evidence label |\n|---:|---|---|---|\n`;
for(const f of manifest.figures)text+=`| ${f.number} | [${safe(f.title)}](../../static/research/anomaly-visuals/${f.assets.desktop.name}) | ${safe(f.section)} | ${safe(f.evidence)} |\n`;
text+='\n## Reproduce / change\n\nSee [visual-authoring instructions](../../research/anomaly-visuals/README.md), [authored specifications](../../research/anomaly-visuals/figures.mjs), and [evidence/asset manifest](../../static/research/anomaly-visuals/manifest.json). Edit the specification and regenerate, rather than editing SVG labels by hand. The manifest and regression suite fail on stale numbers or evidence hashes.\n\n## Limits\n\nThis is an author/assistant factual and rendering review, not independent certification of absolute correctness. The operational-family diagrams are a proposed taxonomy, not a NIST standard. Historical raster images remain unvalidated and explicitly superseded. The Medium edition, native Sentinel ingestion, real-world detection accuracy, automatic containment safety and the previously documented AWS source conflict are unchanged.\n';
text+='\n## Release-gate accessibility follow-up\n\nThe first website CI run exposed color-only caption links and non-focusable horizontal tables. The source now underlines caption citations and uses a keyboard-focusable Markdown table component with a visible focus outline. The browser report includes focused axe checks for both rules in all six viewport/theme configurations. This report remains a pre-release verification snapshot; final deployment status is recorded separately.\n';
text+='\nThe final local follow-up opens all 43 text-equivalent panels before running these checks. It also corrected the wide statistics JSON block so keyboard users can focus and scroll it. The recorded browser results explicitly include expanded-panel coverage.\n';
writeFileSync(resolve(root,dir,'REPORT.md'),text);
console.log('Wrote '+dir+'/REPORT.md');
